In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5])

## numpy array is number only, because numpy is for numbers specifically

array([2, 3, 4, 5])

In [3]:
type([5,6,8])

list

In [5]:
x = np.array([2,3,4])
print(x.dtype)

print(x)

int32
[2 3 4]


In [12]:
y = np.array([5.5,6.5,4.8], dtype = float)

print(y.dtype)

float64


In [17]:
z = np.mat('2,5,4;6,8,9')

print(z[1])

[[6 8 9]]


In [30]:
a = [98,78,58,65,98,41,25]
b = [58,48,52,63,94,73,25]

c = np.array([a,b])

d = np.asarray(c)

print(c)
print(d, '\n')

if c.all() == d.all():
    print('success')

[[98 78 58 65 98 41 25]
 [58 48 52 63 94 73 25]]
[[98 78 58 65 98 41 25]
 [58 48 52 63 94 73 25]] 

success


In [36]:
a = [98,78,58,65,98,41,25]
b = [58,48,52,63,94,73,25]

c = np.array([a,b])

print(type(c))

# datapoint count:
print(c.size)

# number of dimensions, and the elements along each axis
print(c.shape)

# number of dimensions
print(c.ndim)

# data type of each datapoint
print(c.dtype)

<class 'numpy.ndarray'>
14
(2, 7)
int32
2


In [49]:
# a_range (arange, not arrange) and linspace

# base python cannot handle floating point numbers
print(list(range(2,5)))


# first value, last value, step size
a = np.arange(2,10.5,0.4)

# again, first, last, step size
# goes backward from startpoint to endpoint
a[5::-1]
# ! for reverse order starting point has to be larger than endpoint !

[2, 3, 4]


array([4. , 3.6, 3.2, 2.8, 2.4, 2. ])

In [75]:
# Numpy linspace
# equally space elements in a range of numbers

print(np.linspace(2,80,6))

new = np.linspace(2,80, 6, endpoint = True, retstep = True)
# retstep = retention step (print the distance)
newcomer = new[::-1]

# here we can achieve a similar thing with the arange command
print(np.arange(2,80,newcomer[0]))
print(newcomer[0])

[ 2.  17.6 33.2 48.8 64.4 80. ]
[ 2.  17.6 33.2 48.8 64.4]
15.6


In [88]:
# Numpy matrices

# to make a 1d matrix
np.zeros(5)
np.zeros((5))

# to make a 2d matrix
np.zeros((5,6))

# we can make a blank matrix of ones too
np.ones(5)

# matrix multiplication to get a blank matrix of any number
5 * np.ones((2,3))

x = np.arange(1,51).reshape(10,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [252]:
# Generating random numbers

# np.random.seed(x)
# each seed will generate similar data

# np.random.____ 
# rand() — uniform distribution from ZERO to ONE
# randn() — normal distribution
# randint() — random integer matrix

# call function with dimensions of matrix
np.random.rand(10,3)

# same - call function with matrix dimensions
x = np.random.randn(5,5)


# call function, params: low value, high value, numer of datapoints to be selected
np.random.randint(0,10,100)

# we can also input the sample size as a matrix to make it n-dimensional
np.random.randint(0, 100, (5,5))

array([[86, 15, 74, 20, 17],
       [57,  4, 34, 43, 89],
       [86, 33, 71, 10, 11],
       [ 8, 74, 63, 10, 97],
       [20, 30, 66, 94, 13]])

In [259]:
# Numpy condition
# np.clip()
# just like 'clipping' in video games etc. this raises number below the bottom
# margin to the bottom margin, and number that are above the high margin get
# lowered to it

# sample list
a = [-2,-58,1020,52,68]

a = np.clip(a,0,a_max = 100)

# number below bottom raise to ZERO
# number above lowered to ONE HUNDRED
# all other numbers left as they are

# give us the indexes of places with a certain condition
np.where(a < 10)

(array([0, 1], dtype=int64),)

In [261]:
from numpy.random import randint as ri

In [274]:
# reshape sort

d = ri(1, 99, 30)
e = d.reshape(2,3,5)
# number of matrices, rows, columns

print('d:','\n', d)
print('\n')
print('e:','\n',e)


e = d.reshape(3,10)
print('\n')
print('new e:','\n',e)


d: 
 [29 35 80 15 59 57 89 81 81 20 47  4 14 31 64 14 65 27 60 41 84 62 25  5
 39 98 98 45 25 23]


e: 
 [[[29 35 80 15 59]
  [57 89 81 81 20]
  [47  4 14 31 64]]

 [[14 65 27 60 41]
  [84 62 25  5 39]
  [98 98 45 25 23]]]


new e: 
 [[29 35 80 15 59 57 89 81 81 20]
 [47  4 14 31 64 14 65 27 60 41]
 [84 62 25  5 39 98 98 45 25 23]]


In [278]:
# sort data low to high, row-wise
print(np.sort(e, axis = 1))
# by default axis = 1

print('\n')

# sort data low to high, column-wise
print(np.sort(e, axis = 0))

[[15 20 29 35 57 59 80 81 81 89]
 [ 4 14 14 27 31 41 47 60 64 65]
 [ 5 23 25 25 39 45 62 84 98 98]]


[[29  4 14  5 39 14 65 27 25 20]
 [47 35 25 15 59 57 89 45 60 23]
 [84 62 80 31 64 98 98 81 81 41]]


In [293]:
ar = np.arange(0,10,0.2)
print(ar.size)

ar = ar.reshape(5,10)

print(ar, '\n')

# we want all columns, row SIXTH till LAST
# (rows and columns indexed from ZERO)
print(ar[:, 5:])

print('\n')

# columns TWO till END, rows FIFTH till SEVENTH
# !! LAST INDEX ALWAYS EXCLUDED IN OUTPUT, JUST LIKE WITH LINSPACE
print(ar[2:,4:8])


#!!!
# xxx[ g : f ]
# —> g included as first index
# —> f excluded, but f-1 included as last


# xxx[ g , f ]
# —> g,f included, because its a list of indexes

50
[[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
 [2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8]
 [4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8]
 [6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8]
 [8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]] 

[[1.  1.2 1.4 1.6 1.8]
 [3.  3.2 3.4 3.6 3.8]
 [5.  5.2 5.4 5.6 5.8]
 [7.  7.2 7.4 7.6 7.8]
 [9.  9.2 9.4 9.6 9.8]]


[[4.8 5.  5.2 5.4]
 [6.8 7.  7.2 7.4]
 [8.8 9.  9.2 9.4]]


In [296]:
# To update data in a matrix

x = np.arange(0, 50, 2)
y = x.reshape(5,5)


# update a spot:
y[0,2] = 10000
y

array([[    0,     2, 10000,     6,     8],
       [   10,    12,    14,    16,    18],
       [   20,    22,    24,    26,    28],
       [   30,    32,    34,    36,    38],
       [   40,    42,    44,    46,    48]])

In [345]:
# Subsetting

arr = np.array(ri(10,10000,30)).reshape(3, 10)

arr

# this makes a boolean matrix
xyz = [arr>5000]
print(xyz, '\n')

# this multiplies the boolean matrix over the actual matrix to get the desired
# data

zyx = arr[arr>5000]
print(zyx)

print('\n')

print(np.where(zyx < 6000))
print(zyx[np.where(zyx < 6000)])

[array([[ True,  True,  True,  True, False, False,  True,  True,  True,
        False],
       [ True, False,  True, False, False,  True,  True, False,  True,
        False],
       [False, False,  True,  True,  True,  True, False,  True,  True,
        False]])] 

[6657 5216 5401 8143 5399 7219 8837 7491 9007 8505 9954 5143 9796 9076
 5987 5022 9431 6606]


(array([ 1,  2,  4, 11, 14, 15], dtype=int64),)
[5216 5401 5399 5143 5987 5022]


In [357]:
# Matrix multiplication
x = np.array(ri(0,100,20)).reshape(4,5)
y = np.array(ri(0,100,20)).reshape(4,5)

print(x)
print('\n')
print(y)

#multiplication is as easy as this:
z = x*y
print(z)

print((3*x) * (4*y))
print('\n')
print(x-y)
print('\n')
print(y+x)

[[73 62 95 57  9]
 [25 89 19 76 89]
 [25 15 70 10 31]
 [29 68 21 12 95]]


[[18  6 65 62 46]
 [70 34 39 34 24]
 [28 71 17 70  3]
 [58 58 85 84 37]]
[[1314  372 6175 3534  414]
 [1750 3026  741 2584 2136]
 [ 700 1065 1190  700   93]
 [1682 3944 1785 1008 3515]]
[[15768  4464 74100 42408  4968]
 [21000 36312  8892 31008 25632]
 [ 8400 12780 14280  8400  1116]
 [20184 47328 21420 12096 42180]]


[[ 55  56  30  -5 -37]
 [-45  55 -20  42  65]
 [ -3 -56  53 -60  28]
 [-29  10 -64 -72  58]]


[[ 91  68 160 119  55]
 [ 95 123  58 110 113]
 [ 53  86  87  80  34]
 [ 87 126 106  96 132]]


In [ ]:
# Broadcasting — reconciling matrices of different dimensions
# acceptable if a dimension is THE SAME, or ONE
# [SAME, 1], [1, SAME], [SAME, SAME], [1,1]

# TRANSPOSE FUNCTION
# __.T